spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/tracemag

management:
  endpoint:
    threaddump:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081


logging:
  level:
    sql: info
